name: Build and push container image (Release)

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    uses: ./.github/workflows/docker-publish.yml
    with:
      formal: true
    secrets: inherit
    permissions:
      contents: read
      packages: write
