name: Build and push container image (Development)

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  publish:
    uses: ./.github/workflows/docker-publish.yml
    with:
      formal: false
    secrets: inherit
    permissions:
      contents: read
      packages: write
